package teoria.ej18_exceptions;

public class AppDevuelveNumero {

	public static void main(String[] args) throws Exception {
		//System.out.println(DevuelveNumero.devuelveNumeroCaso1(4));
		//System.out.println(DevuelveNumero.devuelveNumeroCaso1(5)); // K:1 M*:3 P:2
		
		//System.out.println(DevuelveNumero.devuelveNumeroCaso2(4)); // K*:2 M*:2 P*:2
		//System.out.println(DevuelveNumero.devuelveNumeroCaso2(5)); // K*:1 M*:1 P*:1
		
		
		//System.out.println(DevuelveNumero.devuelveNumeroCaso3(4)); // K*:otra_cosa M:1 P:1
		System.out.println(DevuelveNumero.devuelveNumeroCaso4(4)); // K*:otra_cosa M:1 P:1
		
		
	}

}
